apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: dXNlcm5hbWU=   # Base64-encoded value for 'username'
  password: cGFzc3dvcmQ=   # Base64-encoded value for 'password'
 